<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title!"API Documentation"}</title>
    <!-- Link to Bootstrap CSS (using unpacked path) -->
    <link href="static-docs-assets/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            display: flex;
        }
        #sidebar {
            min-width: 250px;
            max-width: 250px;
            min-height: 100vh;
            background-color: #f8f9fa;
            padding: 15px;
            position: sticky;
            top: 0;
            height: 100vh;
            overflow-y: auto;
        }
        #main-content {
            flex-grow: 1;
            padding: 30px;
        }
        .nav-link { color: #0d6efd; text-decoration: none; }
        .nav-link.active { font-weight: bold; }
        .nav-link:hover { text-decoration: underline; }
        h2 { margin-top: 2rem; border-bottom: 1px solid #dee2e6; padding-bottom: 0.5rem; }
        h3 { margin-top: 1.5rem; }
        code { background-color: #e9ecef; padding: 0.2em 0.4em; border-radius: 3px; }
        pre code { background-color: transparent; padding: 0; }
        .card { margin-bottom: 1rem; }
        .badge { margin-right: 0.5rem; }
        .response-code { font-weight: bold; }
    </style>
</head>
<body>

<#-- Sidebar Navigation -->
<div id="sidebar" class="d-flex flex-column flex-shrink-0 p-3 bg-light">
    <a href="#" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <span class="fs-4">Navigation</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item"><a href="#overview" class="nav-link active" aria-current="page">Overview</a></li>
        <li><a href="#api-reference" class="nav-link">API Reference</a></li>
        <li><a href="#schemas" class="nav-link">Schemas</a></li>
        <li><a href="#sdk-info" class="nav-link">SDK Info</a></li>
        <li><a href="#examples" class="nav-link">Examples</a></li>
        <hr>
        <li><a href="/swagger-ui.html" class="nav-link" target="_blank">Swagger UI</a></li>
    </ul>
    <hr>
    <small>Generated by SpringDoc Plugin</small>
</div>

<#-- Main Content Area -->
<div id="main-content">

    <#-- Overview Section -->
    <section id="overview">
        <h1>${info.title!"API Title"}</h1>
        <p class="lead">Version: ${info.version!"N/A"}</p>
        <p>${info.description!"No description provided."}</p>

        <#if info.contact??>
            <h3>Contact</h3>
            <p>
                <#if info.contact.name??>Name: ${info.contact.name}<br></#if>
                <#if info.contact.email??>Email: <a href="mailto:${info.contact.email}">${info.contact.email}</a><br></#if>
                <#if info.contact.url??>URL: <a href="${info.contact.url}" target="_blank">${info.contact.url}</a></#if>
            </p>
        </#if>

        <#if info.license??>
            <h3>License</h3>
            <p>
                ${info.license.name!"N/A"}
                <#if info.license.url??>(<a href="${info.license.url}" target="_blank">Details</a>)</#if>
            </p>
        </#if>

        <h3>Servers</h3>
        <#if servers?? && (servers?size > 0)>
            <ul>
                <#list servers as server>
                    <li><code>${server.url}</code> <#if server.description??>- ${server.description}</#if></li>
                </#list>
            </ul>
        <#else>
            <p>No servers defined.</p>
        </#if>
    </section>

    <#-- API Reference Section -->
    <section id="api-reference">
        <h2>API Reference</h2>
        <#if paths?? && (paths?size > 0)>
            <div class="accordion" id="pathsAccordion">
                <#list paths as pathInfo>
                    <#if pathInfo.operations?? && (pathInfo.operations?size > 0)>
                        <#list pathInfo.operations as operation>
                            <#assign operationId = operation.id>
                            <#assign method = operation.method?lower_case>
                            <div class="accordion-item">
                                <h3 class="accordion-header" id="heading_${operationId}">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_${operationId}" aria-expanded="false" aria-controls="collapse_${operationId}">
                                        <span class="badge bg-${method?switch("get","success","post","primary","put","warning","delete","danger","options","info","patch","secondary","head","dark","trace","light")}">${method?upper_case}</span>
                                        <code>${pathInfo.url}</code>
                                        <span class="ms-2">${operation.summary!""}</span>
                                    </button>
                                </h3>
                                <div id="collapse_${operationId}" class="accordion-collapse collapse" aria-labelledby="heading_${operationId}" data-bs-parent="#pathsAccordion">
                                    <div class="accordion-body">
                                        <#if operation.description??><p>${operation.description}</p></#if>
                                        <#if operation.operationId??><p><small>Operation ID: <code>${operation.operationId}</code></small></p></#if>
                                        
                                        <#-- Parameters -->
                                        <#if operation.parameters?? && (operation.parameters?size > 0)>
                                            <h4>Parameters</h4>
                                            <table class="table table-sm table-bordered">
                                                <thead><tr><th>Name</th><th>In</th><th>Required</th><th>Description</th><th>Schema</th></tr></thead>
                                                <tbody>
                                                <#list operation.parameters as param>
                                                    <tr>
                                                        <td><code>${param.name}</code></td>
                                                        <td>${param.in}</td>
                                                        <td><#if param.required>Yes<#else>No</#if></td>
                                                        <td>${param.description!""}</td>
                                                        <td>
                                                            <#if param.schemaRef??>
                                                                <a href="#schema_${param.schemaRef?keep_after_last('/')}"><code>${param.schemaRef?keep_after_last('/')}</code></a>
                                                            <#elseif param.schemaType??>
                                                                <code>${param.schemaType}</code>
                                                                <#if param.schemaFormat??>(${param.schemaFormat})</#if>
                                                            <#else>
                                                                N/A
                                                            </#if>
                                                        </td>
                                                    </tr>
                                                </#list>
                                                </tbody>
                                            </table>
                                        </#if>

                                        <#-- Request Body -->
                                        <#if operation.requestBody??>
                                            <h4>Request Body</h4>
                                            <p>${operation.requestBody.description!""} <#if operation.requestBody.required>(Required)</#if></p>
                                            <#if operation.requestBody.content??>
                                                <#list operation.requestBody.content?keys as contentType>
                                                    <p>Content Type: <code>${contentType}</code></p>
                                                    <#assign schemaInfo = operation.requestBody.content[contentType]>
                                                    <p>Schema: 
                                                    <#if schemaInfo.ref??>
                                                        <a href="#schema_${schemaInfo.ref?keep_after_last('/')}"><code>${schemaInfo.ref?keep_after_last('/')}</code></a>
                                                    <#elseif schemaInfo.type??>
                                                        <code>${schemaInfo.type}</code>
                                                    <#else>
                                                        N/A
                                                    </#if>
                                                    </p>
                                                </#list>
                                            </#if>
                                        </#if>

                                        <#-- Responses -->
                                        <#if operation.responses??>
                                            <h4>Responses</h4>
                                            <table class="table table-sm table-bordered">
                                                <thead><tr><th>Code</th><th>Description</th><th>Content</th></tr></thead>
                                                <tbody>
                                                    <#list operation.responses?keys as responseCode>
                                                    <#assign response = operation.responses[responseCode]>
                                                    <tr>
                                                        <td class="response-code">${responseCode}</td>
                                                        <td>${response.description!""}</td>
                                                        <td>
                                                            <#if response.content?? && response.content?size gt 0>
                                                                <#list response.content?keys as contentType>
                                                                    <div><code>${contentType}</code>
                                                                    <#assign schemaInfo = response.content[contentType]>
                                                                    <#if schemaInfo.ref?? || schemaInfo.type??>
                                                                         Schema: 
                                                                        <#if schemaInfo.ref??>
                                                                            <a href="#schema_${schemaInfo.ref?keep_after_last('/')}"><code>${schemaInfo.ref?keep_after_last('/')}</code></a>
                                                                        <#elseif schemaInfo.type??>
                                                                            <code>${schemaInfo.type}</code>
                                                                        </#if>
                                                                    </#if>
                                                                    </div>
                                                                </#list>
                                                            <#else>
                                                                <em>No Content</em>
                                                            </#if>
                                                        </td>
                                                    </tr>
                                                    </#list>
                                                </tbody>
                                            </table>
                                        </#if>
                                    </div>
                                </div>
                            </div>
                        </#list>
                    </#if>
                </#list>
            </div>
        <#else>
            <p>No paths defined.</p>
        </#if>
    </section>

    <#-- Schemas Section -->
    <section id="schemas">
        <h2>Schemas</h2>
        <#if schemas?? && (schemas?size > 0)>
             <div class="accordion" id="schemasAccordion">
                <#list schemas as schema>
                    <div class="accordion-item" id="schema_${schema.name}">
                        <h3 class="accordion-header" id="heading_schema_${schema.name}">
                             <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_schema_${schema.name}" aria-expanded="false" aria-controls="collapse_schema_${schema.name}">
                                <code>${schema.name}</code>
                            </button>
                        </h3>
                        <div id="collapse_schema_${schema.name}" class="accordion-collapse collapse" aria-labelledby="heading_schema_${schema.name}" data-bs-parent="#schemasAccordion">
                            <div class="accordion-body">
                                <p><strong>Type:</strong> <code>${schema.type!"N/A"}</code></p>
                                <#if schema.format??><p><strong>Format:</strong> <code>${schema.format}</code></p></#if>
                                <#if schema.description??><p><strong>Description:</strong> ${schema.description}</p></#if>
                                <#if schema.requiredFields?? && (schema.requiredFields?size > 0)>
                                    <p><strong>Required Fields:</strong> 
                                        <#list schema.requiredFields as field><code>${field}</code><#sep>, </#list>
                                    </p>
                                </#if>
                                
                                <#if schema.properties?? && (schema.properties?size > 0)>
                                <h4>Properties</h4>
                                <table class="table table-sm table-bordered">
                                    <thead><tr><th>Name</th><th>Type</th><th>Format</th><th>Description</th></tr></thead>
                                    <tbody>
                                        <#list schema.properties as prop>
                                        <tr>
                                            <td><code>${prop.name}</code></td>
                                            <td>
                                                <#if prop.ref??>
                                                     <a href="#schema_${prop.ref?keep_after_last('/')}"><code>${prop.ref?keep_after_last('/')}</code></a>
                                                <#elseif prop.type??>
                                                    <code>${prop.type}</code>
                                                    <#if prop.type == "array" && prop.items??>
                                                        [<#if prop.items.ref??>
                                                            <a href="#schema_${prop.items.ref?keep_after_last('/')}"><code>${prop.items.ref?keep_after_last('/')}</code></a>
                                                        <#elseif prop.items.type??>
                                                            <code>${prop.items.type}</code>
                                                        <#else>N/A</#if>]
                                                    </#if>
                                                <#else>
                                                    N/A
                                                </#if>
                                            </td>
                                            <td><code>${prop.format!""}</code></td>
                                            <td>${prop.description!""}</td>
                                        </tr>
                                        </#list>
                                    </tbody>
                                </table>
                                </#if>
                                
                            </div>
                        </div>
                    </div>
                </#list>
            </div>
        <#else>
            <p>No components or schemas defined.</p>
        </#if>
    </section>

    <#-- SDK Usage & Examples Section -->
    <section id="sdk-usage">
        <h2>SDK Usage & Examples</h2>
        <p>Client SDK source code for Java, TypeScript, and Python is generated during the build and copied into the documentation assets. See the <a href="../../docs/sdk-generator-usage.md" target="_blank">SDK Generator Usage Guide</a> (in the plugin repository) for configuration details and dependency requirements.</p>
        
        <h4>Browse Generated SDK Source:</h4>
        <ul>
            <!-- Link to the directory where the SDK source was copied -->
            <li><a href="sdk/java/">Browse Java SDK (WebClient)</a></li> 
            <li><a href="sdk/ts/">Browse TypeScript SDK (Axios)</a></li>
            <li><a href="sdk/python/">Browse Python SDK</a></li>
        </ul>

        <p><small>Note: Remember to add the necessary runtime dependencies to your client project (see usage guide).</small></p>

        <h4>Basic Usage Examples:</h4>
        <ul class="nav nav-tabs" id="sdkTabs" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="java-tab" data-bs-toggle="tab" data-bs-target="#java-example" type="button" role="tab" aria-controls="java-example" aria-selected="true">Java (WebClient)</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="ts-tab" data-bs-toggle="tab" data-bs-target="#ts-example" type="button" role="tab" aria-controls="ts-example" aria-selected="false">TypeScript (Axios)</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="python-tab" data-bs-toggle="tab" data-bs-target="#python-example" type="button" role="tab" aria-controls="python-example" aria-selected="false">Python</button>
            </li>
        </ul>
        <div class="tab-content pt-3" id="sdkTabContent">
            <div class="tab-pane fade show active" id="java-example" role="tabpanel" aria-labelledby="java-tab">
                <h5>Dependencies (Maven POM):</h5>
                <#noparse>
                <pre><code class="language-xml">&lt;!-- Add Spring WebFlux --&gt;
&lt;dependency&gt;
    &lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;
    &lt;artifactId&gt;spring-boot-starter-webflux&lt;/artifactId&gt;
&lt;/dependency&gt;
&lt;!-- Add Jackson & Other common dependencies (check sdk-generator-usage.md) --&gt;
&lt;dependency&gt;
    &lt;groupId&gt;com.fasterxml.jackson.core&lt;/groupId&gt;
    &lt;artifactId&gt;jackson-databind&lt;/artifactId&gt;
&lt;/dependency&gt;
&lt;dependency&gt; 
    &lt;groupId&gt;jakarta.annotation&lt;/groupId&gt;
    &lt;artifactId&gt;jakarta.annotation-api&lt;/artifactId&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
    &lt;groupId&gt;com.google.code.findbugs&lt;/groupId&gt;
    &lt;artifactId&gt;jsr305&lt;/artifactId&gt;
    &lt;version&gt;3.0.2&lt;/version&gt;
&lt;/dependency&gt;
</code></pre>
                </#noparse>
                <h5>Example Code:</h5>
                <#noparse>
                <pre><code class="language-java">import com.example.petstore.sdk.java.api.PetApi; // Adjust package based on your config
import com.example.petstore.sdk.java.model.Pet;
import org.springframework.web.reactive.function.client.WebClient;
import org.openapitools.client.ApiClient;

// ...

// Configure ApiClient (e.g., with base path)
ApiClient apiClient = new ApiClient(WebClient.builder());
apiClient.setBasePath("http://localhost:8080"); // Set to your service URL

// Instantiate the API
PetApi petApi = new PetApi(apiClient);

// Example: Get Pet by ID (assuming method returns Mono)
Long petId = 1L;
try {
    Pet pet = petApi.getPetById(petId).block(); // block() for simplicity, use async properly
    if (pet != null) {
        System.out.println("Found pet: " + pet.getName());
    } else {
        System.out.println("Pet not found");
    }
} catch (Exception e) {
     System.err.println("Error fetching pet: " + e.getMessage());
}
</code></pre>
                </#noparse>
            </div>
            <div class="tab-pane fade" id="ts-example" role="tabpanel" aria-labelledby="ts-tab">
                <h5>Dependencies (npm/yarn):</h5>
                <#noparse>
                <pre><code class="language-bash">npm install axios
# or
yarn add axios</code></pre>
                </#noparse>
                <h5>Example Code:</h5>
                 <#noparse>
                 <pre><code class="language-typescript">import { PetApi, Configuration } from "./api"; // Adjust import path based on your structure
import { Pet } from "./common"; // Adjust import path

const config = new Configuration({
    basePath: "http://localhost:8080", // Set to your service URL
});

const petApi = new PetApi(config);

async function getPet() {
    const petId = 1;
    try {
        const response = await petApi.getPetById(petId);
        const pet: Pet = response.data;
        console.log(`Found pet: ${pet.name}`);
    } catch (error) {
        console.error(`Error fetching pet: ${error}`);
    }
}

getPet();
</code></pre>
                </#noparse>
            </div>
            <div class="tab-pane fade" id="python-example" role="tabpanel" aria-labelledby="python-tab">
                <h5>Dependencies (pip):</h5>
                <#noparse>
                <pre><code class="language-bash">pip install urllib3 requests python-dateutil
# (Check generated requirements.txt for full list)</code></pre>
                </#noparse>
                <h5>Example Code:</h5>
                <#noparse>
                <pre><code class="language-python">import petstore_sdk # Adjust based on packageName config
from petstore_sdk.rest import ApiException
from pprint import pprint

# Configure API client
configuration = petstore_sdk.Configuration(
    host = "http://localhost:8080" # Set to your service URL
)

# Enter a context with an instance of the api client
with petstore_sdk.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = petstore_sdk.PetApi(api_client)
    pet_id = 1

    try:
        # Find pet by ID
        api_response = api_instance.get_pet_by_id(pet_id)
        pprint(f"Found pet: {api_response.name}")
    except ApiException as e:
        print(f"Exception when calling PetApi->get_pet_by_id: {e}\n")

</code></pre>
                </#noparse>
            </div>
        </div>
    </section>

</div>

<!-- Link to Bootstrap JS (using unpacked path) -->
<script src="static-docs-assets/bootstrap.bundle.min.js"></script>
<script>
    // Smooth scrolling for sidebar links
    document.querySelectorAll('#sidebar a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            const targetId = this.getAttribute('href');
            const targetElement = document.querySelector(targetId);
            if(targetElement) {
                 targetElement.scrollIntoView({ behavior: 'smooth' });
                 // Update active link state
                 document.querySelectorAll('#sidebar .nav-link').forEach(link => link.classList.remove('active'));
                 this.classList.add('active');
            }
        });
    });
</script>
</body>
</html> 