apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springdoc-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
  - host: api.example.com
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: springdoc-demo
            port:
              name: api
      - path: /docs(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: springdoc-demo
            port:
              name: docs 